import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { AlertsPage } from './alerts-page';

describe('AlertsPage', () => {
  let fixture: ComponentFixture<AlertsPage>; let http: HttpTestingController;
  beforeEach(async () => { await TestBed.configureTestingModule({ imports: [AlertsPage], providers: [provideHttpClient(), provideHttpClientTesting(), provideRouter([])] }).compileComponents(); fixture = TestBed.createComponent(AlertsPage); http = TestBed.inject(HttpTestingController); fixture.detectChanges(); http.expectOne('/api/communities').flush([]); fixture.detectChanges(); });
  afterEach(() => http.verify());
  it('starts without querying or showing alert results', () => { expect(fixture.nativeElement.textContent).toContain('Seleccione los filtros'); expect(fixture.nativeElement.querySelectorAll('.alert-card').length).toBe(0); });
  it('applies filters manually and clears back to the initial state', () => { (fixture.nativeElement.querySelector('.primary') as HTMLButtonElement).click(); const request = http.expectOne('/api/alerts?page=1&pageSize=20'); request.flush({ data: [], pageIndex:1, pageSize:20, totalCount:0, totalPages:0, hasPrevious:false, hasNext:false }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('No se encontraron alertas'); const buttons = [...fixture.nativeElement.querySelectorAll('.filters button')] as HTMLButtonElement[]; buttons[1].click(); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Seleccione los filtros'); });
  it('sends selected community, variable and level before pagination', () => { Object.assign(fixture.componentInstance, { communityFilter:'c1', variableFilter:'Temperature', levelFilter:'Red' }); (fixture.nativeElement.querySelector('.primary') as HTMLButtonElement).click(); http.expectOne('/api/alerts?page=1&pageSize=20&communityId=c1&variable=Temperature&level=Red').flush({ data: [], pageIndex:1, pageSize:20, totalCount:0, totalPages:0, hasPrevious:false, hasNext:false }); });
  it('renders one page-size selector and no pagination for empty results', () => { expect(fixture.nativeElement.querySelectorAll('select').length).toBe(4); (fixture.nativeElement.querySelector('.primary') as HTMLButtonElement).click(); http.expectOne('/api/alerts?page=1&pageSize=20').flush({ data:[], pageIndex:1, pageSize:20, totalCount:0, totalPages:0, hasPrevious:false, hasNext:false }); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('.pagination')).toBeNull(); });
  it('changes page size from page one while preserving active filters', () => { Object.assign(fixture.componentInstance, { applied:true, pageIndex:3, communityFilter:'c1', pageSize:10 }); (fixture.componentInstance as any).changePageSize(); http.expectOne('/api/alerts?page=1&pageSize=10&communityId=c1').flush({ data:[], pageIndex:1, pageSize:10, totalCount:0, totalPages:0, hasPrevious:false, hasNext:false }); expect((fixture.componentInstance as any).pageIndex).toBe(1); });
});
